/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TruthHubRouteImport } from './routes/truth-hub'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OfficialsIndexRouteImport } from './routes/officials.index'
import { Route as BillsIndexRouteImport } from './routes/bills.index'
import { Route as OfficialsOfficialIdRouteImport } from './routes/officials.$officialId'
import { Route as BillsBillIdRouteImport } from './routes/bills.$billId'

const TruthHubRoute = TruthHubRouteImport.update({
  id: '/truth-hub',
  path: '/truth-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialsIndexRoute = OfficialsIndexRouteImport.update({
  id: '/officials/',
  path: '/officials/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialsOfficialIdRoute = OfficialsOfficialIdRouteImport.update({
  id: '/officials/$officialId',
  path: '/officials/$officialId',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsBillIdRoute = BillsBillIdRouteImport.update({
  id: '/bills/$billId',
  path: '/bills/$billId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/truth-hub': typeof TruthHubRoute
  '/bills/$billId': typeof BillsBillIdRoute
  '/officials/$officialId': typeof OfficialsOfficialIdRoute
  '/bills/': typeof BillsIndexRoute
  '/officials/': typeof OfficialsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/truth-hub': typeof TruthHubRoute
  '/bills/$billId': typeof BillsBillIdRoute
  '/officials/$officialId': typeof OfficialsOfficialIdRoute
  '/bills': typeof BillsIndexRoute
  '/officials': typeof OfficialsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/truth-hub': typeof TruthHubRoute
  '/bills/$billId': typeof BillsBillIdRoute
  '/officials/$officialId': typeof OfficialsOfficialIdRoute
  '/bills/': typeof BillsIndexRoute
  '/officials/': typeof OfficialsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/services'
    | '/signup'
    | '/truth-hub'
    | '/bills/$billId'
    | '/officials/$officialId'
    | '/bills/'
    | '/officials/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/services'
    | '/signup'
    | '/truth-hub'
    | '/bills/$billId'
    | '/officials/$officialId'
    | '/bills'
    | '/officials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/services'
    | '/signup'
    | '/truth-hub'
    | '/bills/$billId'
    | '/officials/$officialId'
    | '/bills/'
    | '/officials/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  TruthHubRoute: typeof TruthHubRoute
  BillsBillIdRoute: typeof BillsBillIdRoute
  OfficialsOfficialIdRoute: typeof OfficialsOfficialIdRoute
  BillsIndexRoute: typeof BillsIndexRoute
  OfficialsIndexRoute: typeof OfficialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/truth-hub': {
      id: '/truth-hub'
      path: '/truth-hub'
      fullPath: '/truth-hub'
      preLoaderRoute: typeof TruthHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officials/': {
      id: '/officials/'
      path: '/officials'
      fullPath: '/officials/'
      preLoaderRoute: typeof OfficialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/': {
      id: '/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officials/$officialId': {
      id: '/officials/$officialId'
      path: '/officials/$officialId'
      fullPath: '/officials/$officialId'
      preLoaderRoute: typeof OfficialsOfficialIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$billId': {
      id: '/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof BillsBillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  TruthHubRoute: TruthHubRoute,
  BillsBillIdRoute: BillsBillIdRoute,
  OfficialsOfficialIdRoute: OfficialsOfficialIdRoute,
  BillsIndexRoute: BillsIndexRoute,
  OfficialsIndexRoute: OfficialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
